### ISSUE TITLE
Find better alternative to prevent duplicated Slack messages

### ISSUE THREAD

**Issue by brh55** [brh55/slack-contentful#2]
When publishing a change, Contentful updates it across various CDNs, and submits individual outgoing hook for each CDN update. Currently, the bot prevents the same EntryID within a 10 minute span to be considered a "new publish change." Since most users are concern about when a publish change is actually happening, it makes sense. But ideally it would be nice to find a better way to filter duplicates, and will allow for a more specific level of notifications.

**Comment by brh55** [comment]
Code is located here within `server.js`

```
if (entryCache.get(key) !== true) {
   var message = messageCtrl.buildMessage(req.body);
   slackService.sendMessage(message);
   // Store Entries in ID-Revison#: true -- for 10 Minutes
   entryCache.set(key, true, 600);
}
```

**Comment by TimBeyer** [comment]
@brh55 Theoretically it should not happen that hooks call you several times for the same update. There is retry logic though for failing requests, so may it be possible that you don't respond with a `200` in time?
